#!/bin/bash

set -e

if [ "$#" -lt "5" ]; then
echo
echo "USAGE: upload.sh [PROJECT] [IPA FILE] [APPLE ID] [USERNAME] [PASSWORD]";
echo
echo "PROJECT       Name of XCode project, without file extention"
echo "IPA FILE      The .ipa file generated by the build process"
echo "APPLE ID      Apple ID, as shown in iTunes Connect"
echo "USERNAME      Username of account used for uploading application"
echo "PASSWORD      Password of account used for uploading application"
echo
exit
fi

TEMPDIR=build/itsmp

PROJECT="$1"
IPA_FILE="$2"
APP_ID="$3"
USER="$4"
PASS="$5"

echo
echo "PROJECT   $PROJECT"
echo "IPA FILE  $IPA_FILE"
echo "APPLE ID  $APP_ID"
echo

IPA_FILENAME=$(basename $IPA_FILE)
MD5=$(md5 -q $IPA_FILE)
BYTESIZE=$(stat -f "%z" $IPA_FILE)

test -d ${TEMPDIR} && rm -rf ${TEMPDIR}
mkdir ${TEMPDIR}
mkdir ${TEMPDIR}/${PROJECT}.itmsp

cat <<EOM > ${TEMPDIR}/${PROJECT}.itmsp/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<package version="software4.7" xmlns="http://apple.com/itunes/importer">
<software_assets apple_id="$APP_ID">
<asset type="bundle">
<data_file>
<file_name>$IPA_FILENAME</file_name>
<checksum type="md5">$MD5</checksum>
<size>$BYTESIZE</size>
</data_file>
</asset>
</software_assets>
</package>
EOM

cp ${IPA_FILE} $TEMPDIR/${PROJECT}.itmsp

/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/bin/iTMSTransporter -m upload -f ${TEMPDIR} -u "$USER" -p "$PASS" -v detailed
